language: generic
dist: xenial
services:
  - docker

install:
  docker-compose build

script:
  - docker-compose run modelchecker pytest
  - docker-compose run modelchecker flake8

deploy:
  provider: pypi
  user: "nens"
  password:
    secure: LongStringThatNeedsToBeSetByReinout
  # (travis encrypt NENS-PASSWORD --com --add deploy.password)
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true

notifications:
  email: false
