language: generic
dist: xenial

services:
  - docker

install:
  docker-compose build

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose run postgis  # initialize the empty 3Di database

script:
  - docker-compose run modelchecker pytest
  - docker-compose run modelchecker flake8

notifications:
  email: false
