language: generic
dist: xenial
services:
  - docker

install:
  docker-compose build

script:
  - docker-compose run modelchecker pytest
  - docker-compose run modelchecker flake8

deploy:
  provider: pypi
  user: "nens"
  password:
    secure: "Eo45ld6lTiCGWzPGYwEm8EtVAxRlbt/zb4y2F+ifqsmPkYMl+sKXto8FFJvLtA+1DB9JGqR3MHE/jfp4s2MJ9mkBFJH/InYSdkLZ63WC2Ro7XkUuXDQ3H/zv6g/xIwANXKZS5ConrR5uguDHPkSjG/l0gZ12HsZ0pnR+UILSXuXnb7upG1luPbgSR2kd5VwABcAoucyv39jwSBfivIkFjYS+tcfV+4GrlX17OgnEap/nO7xE7LvVexAS76AadCMwgqCU7o7cZmdL/a0ej4lBrchglCO1ptKiY1NypIcOiF6DeY2t23AfkmzKsymYP/CW2jbFatEc11hY7a4vz3feHsfE/vawIX26c7/o95Qo+6ha0nPyibfPPb98qRoz8GCb/Hz+LSfZOO3Xw6uBqJin7tqaKKYBkIh9MOHqUzZRjNqa/b4SgpoJht6vaVoZl/LjOpV0oVVQK0jBQDEd4mDyyL7A+SLExfSWxe8P4BBlikKCOM/lMB86qAfI5pZ+aDtZcUEVspfdrIkf+BMG+D2k3u02UZUwH3StoUCVO6Rn1ucrPbYE9kRlMSOAZr72Q6FuCPSWlX85yi87zQnOzCgTryxuVk4HysUGWgXlAsRUjyYm0ZUwi5qfnNCetgTFSf7Cp7akHleqL0osxvc98RVSXgoOdSXlkZ6Ani47LC1wj8k="
  # (travis encrypt NENS-PASSWORD --com)
  on:
    tags: true
  distributions: "sdist bdist_wheel"
  skip_existing: true

notifications:
  email: false
